# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaSistema.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_janelaPrincipal(object):
    def setupUi(self, janelaPrincipal):
        janelaPrincipal.setObjectName("janelaPrincipal")
        janelaPrincipal.resize(300, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(janelaPrincipal.sizePolicy().hasHeightForWidth())
        janelaPrincipal.setSizePolicy(sizePolicy)
        janelaPrincipal.setMinimumSize(QtCore.QSize(300, 100))
        janelaPrincipal.setMaximumSize(QtCore.QSize(300, 100))
        self.centralwidget = QtWidgets.QWidget(janelaPrincipal)
        self.centralwidget.setMinimumSize(QtCore.QSize(300, 100))
        self.centralwidget.setMaximumSize(QtCore.QSize(300, 100))
        self.centralwidget.setObjectName("centralwidget")
        self.brilho = QtWidgets.QSlider(self.centralwidget)
        self.brilho.setGeometry(QtCore.QRect(20, 0, 261, 16))
        self.brilho.setOrientation(QtCore.Qt.Horizontal)
        self.brilho.setObjectName("brilho")
        self.valor = QtWidgets.QLabel(self.centralwidget)
        self.valor.setGeometry(QtCore.QRect(160, 20, 31, 21))
        self.valor.setObjectName("valor")
        self.nivel = QtWidgets.QLabel(self.centralwidget)
        self.nivel.setGeometry(QtCore.QRect(110, 20, 67, 22))
        self.nivel.setObjectName("nivel")
        janelaPrincipal.setCentralWidget(self.centralwidget)

        self.retranslateUi(janelaPrincipal)
        QtCore.QMetaObject.connectSlotsByName(janelaPrincipal)

    def retranslateUi(self, janelaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        janelaPrincipal.setWindowTitle(_translate("janelaPrincipal", "BRILHO LINUX"))
        self.valor.setText(_translate("janelaPrincipal", "0.0"))
        self.nivel.setText(_translate("janelaPrincipal", "Nivel:"))
